name: Cloud Servers build

on: workflow_dispatch

permissions:
  contents: read
  id-token: write

env:
  ORGANIZATION_NAME: coldbox-modules
  CFML_ENGINE: boxlang@1

jobs:
  generate_report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        report: ["workflows_status.json", "excluded_repos.json", "summary.json"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Auth GitHub CLI
        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
    
      - name: Execute report script
        run: ./report.sh ${{ env.ORGANIZATION_NAME }} ${{ env.CFML_ENGINE }}
      
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
            name: ${{ matrix.report }}
            path: ./${{ matrix.report }}