name: Jobs executions for given CFML engine

on: workflow_dispatch

permissions:
  contents: read
  id-token: write

env:
  ORGANIZATION_NAME: ${{ github.repository_owner }}

jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Auth GitHub CLI
        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
    
      - name: Execute report script
        run: ./report.sh ${{ env.ORGANIZATION_NAME }}
      
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
            name: Boxlang tests report
            path: ./*.json
        
      - name: Cat summary report
        run: |
          echo "REPOS_WITH_TEST=$(cat summary.json | jq -r '.repositories_with_tests')" >> $GITHUB_ENV
          echo "REPOS_WITHOUT_TEST=$(cat summary.json | jq -r '.repositories_without_tests')" >> $GITHUB_ENV
          echo "ANALYZED_REPOS=$(cat summary.json | jq -r '.analyzed_repositories')" >> $GITHUB_ENV
          echo "SUCCESS_TESTS=$(cat summary.json | jq -r '.job_conclusions.success')" >> $GITHUB_ENV
          echo "FAILED_TESTS=$(cat summary.json | jq -r '.job_conclusions.failure')" >> $GITHUB_ENV

      - name: Inform Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: boxlang
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_ICON_EMOJI: ":bell:"
          SLACK_MESSAGE: "${{ env.ANALYZED_REPOS}} repositories analyzed. ${{ env.REPOS_WITH_TEST }} with test :grinning: and ${{ env.REPOS_WITHOUT_TEST }} without tests :face_with_spiral_eyes:"
          SLACK_TITLE: "Boxlang tests report"
          SLACK_USERNAME: CI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          MSG_MINIMAL: true